### ISSUE TITLE
review XLSX JavaScript library

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo_data#30]
The app should to be able to read : XLSX, ODS (optional for first version) and CSV format.
Let's review JS lib options to read the first two. 
Some years ago @Yomguithereal and I used this one https://www.npmjs.com/package/xlsx

**Comment by Yomguithereal** [comment]
Why, oh Romeo, why?

**Comment by paulgirard** [comment]
Because of Béatrice.

XLSX lib does support ODS format too.
