### ISSUE TITLE
Specs about data validation errors strategy

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo_data#33]
# Validation/correction protocol

## 1. chuncking validation process ?

Because of technical constraints we need to run validation by chuncks if the volume is to large.
(Actually I don't understand why... it's not such a complicated process...)
Thus, we should probably start by chunking input data and run one validation by chunck to collect all the errors.

## 2. Structure error 
If there is a structure error wrong columns or missing mandatory columns.
Display those and ask the suer to reupload a correct file.
We don't want to let the user to go further until the structure is right.

@mydu : I am not sure how datapackage handle structure issues ?
(I added required fields in the datapackage)

### UniqueKey error
this constraint can't be validated if the validation is chuncked.
- change value to a unique value of the field
    
The only unique constraint so fare is on the Id column
We might remove the column completely or generate it.
We have to discuss this with Béatrice.

## 3. Aggregating errors

It might be more efficient to group errors of the same type for the same column.s for the same original value.s (**/!\** there is one case where error concerns multiple columns : foreignkey on multiple columns). This implies to run the validation of the complete dataset (see 1. about chuncking).

With such an aggregation of errors, we can show a summary of the work to be done.
For each columns, we can output :
- the total number of errors for this column
- the total number of rows affected for this column
- the number of different values for this column (to contextualize the number of errors)
 
Then we could list the work to be done as a list/table(?) of common errors being composed of : 
- type
- column.s affected
- error message (should be the same across the aggregate ?)
- number of rows affected (key to sort the list)
- original value.s
- modification component => this component would modify all the rows with the same original value.s to solve all the errors at once (see 4. about modification components)
- table to explore the affected rows (not mandatory bu might be useful)

Pro : 
- show a summary of the work to be done
- helps identify systematic errors
- we can let the user fix a long list of errors at once
- we don't have to revalidate at each modification cause aggregating remove dependencies between errors across rows. We can still decide to run the validation only on the rows affected.

Cons :
- we lose the affordance of the table mode which is naturally linked to the data input
- aggregating errors is not needed for local errors like typo ones but still works

### Format error 
Solving such an error implies modifying input data to match the expected format.
It's an input field which depends on the field type.
Input validation might be automatised as data package follows Json schema specification ?

```
Systematic format errors can occure. In such cases the system described here isn't efficient.
But systematic format error might be spotted right away by the user tanks to the summary.
In which case she.he should use search replace or export settings to solve those systematic errors upstream.
```

### Enum constraint
Quite the same thing as format error but enum can be efficiently corrected by the aggregation system.
Solving one wrong enum will affect all the rows so the actions are limited to the number of wrong enums (and not by affected rows).

Edition validation :  select input field folowing json schema speficiation    
    
### ForeignKey error 

ForeignKey errors are more complex. Not only they concern other tables, they might concern ore than one data field.
Two possible ways to solve it :
- the original value in the flow has to be changed (very rare)
- the original value is missing in the corresponding table

For now let's only consider the second option.
This option can be solved with  a form to add a row in the foreigntable with: 
- the foreignFields pre-filled with the original value.s
- blanck fields for other fields

The problem is that those fields to be field are often themselves foreignKeys to third tables (RICnames...). In which case this should be a lookup field or a add extra row in the third table... 

Maybe Foreign key modification component should be designed and not generated from schema ?  

## storing external table data locally 

To resolve foreignkey error and to be able to revalidate data after foreign key modifications we need to store external data table locally. We can't rely on the github version after foreign key modifications.

## 5. Re-Validation

After user actions we need to revalidate.
First modifications should be validated at the input stage.
Then we might want to revalidate the data rows which has been affected.

We could decide to do it locally after each modification by running a validation of the row affected.
Or we could let the user trigger a validation process on the complete data set taking into account the modifications made.

**Comment by paulgirard** [comment]
@mydu please review and comment this spec. If we agree on this we can split this in more precise issues.

**Comment by mydu** [comment]
- **2.Structure error** is implemented when uploading (please test it here http://medialab.github.io/ricardo_data/), which is before **1.chunking process**
- **unique key check** is skipped for now, which means we only have **format check** and **foreignkeys check**
- **3. Aggregating errors** looks good for me and I can start prototype with **format check**, for  **foreignkeys check** I found a special case for **reporting** field is checked in different table https://github.com/medialab/ricardo_data/blob/master/datapackage.json#L175-L178 and
https://github.com/medialab/ricardo_data/blob/master/datapackage.json#L183-L186
dont know how tableschema handle this case yet, and what is the expected behavior if one is valid and one is not, or both are invalid?
- **step 4 and 5** - will discuss with @robindemourat if the get the correct result from **step 3**

**Comment by paulgirard** [comment]
Ok structure errors handling works !
Yes let unique key aside.

For **foreign key**, indeed reporting as two references... 
Let's see how table schema handle this..  I would assume that both references should be tested and one error should be emitted by reference even if on the same field.

**Comment by paulgirard** [comment]
About reporting multiple **Foreign keys** :   
https://github.com/mydu/tableschema-js/blob/3e70310f6af19a9a1edfda3d7f666e7eec45fcaa/src/table.js#L167-L169 

The validation process loop on the foreign keys definition and treat them independently.
I don't see any issues related to our case where the reporting fields is mentioned is two FK.
If the field is missing on both tables => two errors will be emitted.

**Comment by paulgirard** [comment]
I created independent issues to reflect all of this spec. Closing this one.
